language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
  - TEST_SUITE=unit
  - TEST_SUITE=mongo_integration
  - TEST_SUITE=memcached_integration

services:
  - mongodb
  - memcached

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - phpenv config-add travis_config.ini

script: phpunit --coverage-text --testsuite $TEST_SUITE